In [2]:
import seaborn as sns
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({
    'city':  ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [4]:
list(df.groupby('city'))

[('London',
       city  price
  1  London    150),
 ('New York',
         city  price
  0  New York    200
  4  New York    180),
 ('Paris',
      city  price
  2  Paris    300
  5  Paris    320),
 ('Tokyo',
      city  price
  3  Tokyo    250)]

In [5]:
list(df.groupby('city')['price'])

[('London',
  1    150
  Name: price, dtype: int64),
 ('New York',
  0    200
  4    180
  Name: price, dtype: int64),
 ('Paris',
  2    300
  5    320
  Name: price, dtype: int64),
 ('Tokyo',
  3    250
  Name: price, dtype: int64)]

In [6]:
df.groupby('city')['price'].mean()

city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [7]:
mean_price = df.groupby('city')['price'].mean()
mean_price

city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [8]:
df['city']

0    New York
1      London
2       Paris
3       Tokyo
4    New York
5       Paris
Name: city, dtype: str

In [9]:
df['city_encoded'] = df['city'].map(mean_price)
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

## Feature Scaling
a data preprocessing technique used in machine learning to normalize the range of independent variables (features)

In [10]:
df = pd.DataFrame({
    'Age':[22,34,42,23],
    'Income':[23333,34222,43343,12221]

})
df

   Age  Income
0   22   23333
1   34   34222
2   42   43343
3   23   12221

In [12]:
#Standardization(standard Scaling)---> z-score

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)
scaled_data
df1 = pd.DataFrame(scaled_data,columns=df.columns)
df1

        Age    Income
0 -0.999083 -0.423960
1  0.454129  0.509279
2  1.422936  1.290992
3 -0.877982 -1.376311

In [13]:
max(df1['Age']),min(df1['Age'])

(1.4229363786451807, -0.9990829892615098)

In [14]:
#Min-Max Scaling (Normalization)


from sklearn.preprocessing import MinMaxScaler

df = pd.DataFrame({
    'Score' : [45,60,75,90]
})
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
df2 = pd.DataFrame(scaled_data,columns=df.columns)
df2

      Score
0  0.000000
1  0.333333
2  0.666667
3  1.000000

In [19]:
#Robust Scaling (X - median / IQR)

a= np.mean([1,2,3,4,5])
b = np.mean([1,2,3,4,1000])
a,b

(np.float64(3.0), np.float64(202.0))

In [23]:
from sklearn.preprocessing import RobustScaler
df = pd.DataFrame({
    'Income':[30000,35000,40000,150000]
    })
scaler = RobustScaler()
scaled_data = scaler.fit_transform(df)
df2 = pd.DataFrame(scaled_data,columns = df.columns)
df2

     Income
0 -0.222222
1 -0.074074
2  0.074074
3  3.333333

In [25]:
#Max Absolute Scaling(-1 to 1) --> X_scaled = X/max(abs(X))

from sklearn.preprocessing import MaxAbsScaler

df = pd.DataFrame({
    'Value':[-5000,-2000,0,3000,8000]
})
scaler = MaxAbsScaler()
scaled_data = scaler.fit_transform(df)
df5 = pd.DataFrame(scaled_data,columns=df.columns)
df5

   Value
0 -0.625
1 -0.250
2  0.000
3  0.375
4  1.000

In [31]:
#Log Transformation 
df = pd.DataFrame({
    'Income':[30000,35000,40000,150000]
})
df['Log_income'] = np.log1p(df['Income'])
df

   Income  Log_income
0   30000   10.308986
1   35000   10.463132
2   40000   10.596660
3  150000   11.918397

In [33]:
#X_transformed = (X^lambda-1)/lambda

from sklearn.preprocessing import PowerTransformer

df = pd.DataFrame({
    'Usage':[5,6,32,12,55]
})

transformer = PowerTransformer(method='yeo-johnson')
transformed_data = transformer.fit_transform(df)
df2 = pd.DataFrame(transformed_data,columns=df.columns)
df2

      Usage
0 -1.189314
1 -0.955375
2  0.897636
3 -0.114537
4  1.361588