In [ ]:
import pandas as pd
df = pd.read_csv('Day8_sales.csv')

In [22]:
df.head()

         date  store  item  sales
0  2013-01-01      1     1     13
1  2013-01-02      1     1     11
2  2013-01-03      1     1     14
3  2013-01-04      1     1     13
4  2013-01-05      1     1     10

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    913000 non-null  str
 1   store   913000 non-null  int64
 2   item    913000 non-null  int64
 3   sales   913000 non-null  int64
dtypes: int64(3), str(1)
memory usage: 27.9 MB

In [24]:
#Date Based Features
df['Date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    913000 non-null  str
 1   store   913000 non-null  int64
 2   item    913000 non-null  int64
 3   sales   913000 non-null  int64
 4   Date    913000 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(3), str(1)
memory usage: 34.8 MB

In [25]:
#Lag Features --> Lag1 ,Lag2, previous
'''
Date Sales Lag1 Lag2
Jan1  13   Nan  Nan
jan2  11   13   Nan
jan3  14   11   13
'''

#Rolling Statistics

'''

3 Day rolling mean
sales
13
11
14
(13+11+14)/3

'''

#Rolling Min , Max


'''
13 11 14 13 19 10 ------> 10 , 19
'''


#Rolling s.d. 
'''
Stable - 10,11,10,11 ---> easier to predict
Volatile - 2,20,5,29,39,3
'''


#Difference Features --> Captures Momentum
'''
Sales Difference
13        Nan
11        -2
14        +3  
'''

#Percentage Change
'''
(Today - Yesterday)/Yesterday
(14 - 11) / 11
'''

#Seasonal Features --> repearing Value --> day of week , quarter

#Cyclical Encoding --> Sunday = 6 , Monday = 0 , sin(day), cos(day)

#Trend Features --> Model Leaning upward or downward

'\n(Today - Yesterday)/Yesterday\n(14 - 11) / 11\n'

In [26]:
df['Date'].dt.month

0          1
1          1
2          1
3          1
4          1
          ..
912995    12
912996    12
912997    12
912998    12
912999    12
Name: Date, Length: 913000, dtype: int32

In [27]:
#df = df.sort_values('Date')
#df.sample(10)

In [28]:
df['year'] = df['Date'].dt.year
df

              date  store  item  sales       Date  year
0       2013-01-01      1     1     13 2013-01-01  2013
1       2013-01-02      1     1     11 2013-01-02  2013
2       2013-01-03      1     1     14 2013-01-03  2013
3       2013-01-04      1     1     13 2013-01-04  2013
4       2013-01-05      1     1     10 2013-01-05  2013
...            ...    ...   ...    ...        ...   ...
912995  2017-12-27     10    50     63 2017-12-27  2017
912996  2017-12-28     10    50     59 2017-12-28  2017
912997  2017-12-29     10    50     74 2017-12-29  2017
912998  2017-12-30     10    50     62 2017-12-30  2017
912999  2017-12-31     10    50     82 2017-12-31  2017

[913000 rows x 6 columns]

In [29]:
df['month'] = df['Date'].dt.month
df

              date  store  item  sales       Date  year  month
0       2013-01-01      1     1     13 2013-01-01  2013      1
1       2013-01-02      1     1     11 2013-01-02  2013      1
2       2013-01-03      1     1     14 2013-01-03  2013      1
3       2013-01-04      1     1     13 2013-01-04  2013      1
4       2013-01-05      1     1     10 2013-01-05  2013      1
...            ...    ...   ...    ...        ...   ...    ...
912995  2017-12-27     10    50     63 2017-12-27  2017     12
912996  2017-12-28     10    50     59 2017-12-28  2017     12
912997  2017-12-29     10    50     74 2017-12-29  2017     12
912998  2017-12-30     10    50     62 2017-12-30  2017     12
912999  2017-12-31     10    50     82 2017-12-31  2017     12

[913000 rows x 7 columns]

In [30]:
df['day'] = df['Date'].dt.day
df

              date  store  item  sales       Date  year  month  day
0       2013-01-01      1     1     13 2013-01-01  2013      1    1
1       2013-01-02      1     1     11 2013-01-02  2013      1    2
2       2013-01-03      1     1     14 2013-01-03  2013      1    3
3       2013-01-04      1     1     13 2013-01-04  2013      1    4
4       2013-01-05      1     1     10 2013-01-05  2013      1    5
...            ...    ...   ...    ...        ...   ...    ...  ...
912995  2017-12-27     10    50     63 2017-12-27  2017     12   27
912996  2017-12-28     10    50     59 2017-12-28  2017     12   28
912997  2017-12-29     10    50     74 2017-12-29  2017     12   29
912998  2017-12-30     10    50     62 2017-12-30  2017     12   30
912999  2017-12-31     10    50     82 2017-12-31  2017     12   31

[913000 rows x 8 columns]

In [31]:
df['dayofweek'] = df['Date'].dt.day_of_week
df.sample(3)

              date  store  item  sales       Date  year  month  day  dayofweek
675298  2017-02-13     10    37     13 2017-02-13  2017      2   13          0
642060  2016-02-09      2    36     59 2016-02-09  2016      2    9          1
607248  2015-10-14      3    34     14 2015-10-14  2015     10   14          2

In [32]:
df['weekofyear'] = df['Date'].dt.isocalendar().week
df.sample(5)

,date,store,item,sales,Date,year,month,day,dayofweek,weekofyear
441723,2017-07-16,2,25,193,2017-07-16,2017,7,16,6,28
898190,2017-06-13,2,50,106,2017-06-13,2017,6,13,1,24
498224,2017-04-02,3,28,125,2017-04-02,2017,4,2,6,13
329309,2014-09-22,1,19,26,2014-09-22,2014,9,22,0,39
244817,2013-05-14,5,14,34,2013-05-14,2013,5,14,1,20

In [33]:
df['quarter'] = df['Date'].dt.quarter
df.sample(5)

,date,store,item,sales,Date,year,month,day,dayofweek,weekofyear,quarter
382836,2016-04-17,10,21,52,2016-04-17,2016,4,17,6,15,2
194688,2016-02-07,7,11,44,2016-02-07,2016,2,7,6,5,1
428658,2016-10-06,5,24,50,2016-10-06,2016,10,6,3,40,4
162716,2013-07-22,10,9,51,2013-07-22,2013,7,22,0,30,3
817055,2015-04-14,8,45,89,2015-04-14,2015,4,14,1,16,2

In [34]:
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)
df

,date,store,item,sales,Date,year,month,day,dayofweek,weekofyear,quarter,is_weekend
0,2013-01-01,1,1,13,2013-01-01,2013,1,1,1,1,1,0
1,2013-01-02,1,1,11,2013-01-02,2013,1,2,2,1,1,0
2,2013-01-03,1,1,14,2013-01-03,2013,1,3,3,1,1,0
3,2013-01-04,1,1,13,2013-01-04,2013,1,4,4,1,1,0
4,2013-01-05,1,1,10,2013-01-05,2013,1,5,5,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
912995,2017-12-27,10,50,63,2017-12-27,2017,12,27,2,52,4,0
912996,2017-12-28,10,50,59,2017-12-28,2017,12,28,3,52,4,0
912997,2017-12-29,10,50,74,2017-12-29,2017,12,29,4,52,4,0
912998,2017-12-30,10,50,62,2017-12-30,2017,12,30,5,52,4,1
912999,2017-12-31,10,50,82,2017-12-31,2017,12,31,6,52,4,1

### Lag Features

In [39]:
df['Lag_1'] = df['sales'].shift(1)
df.head(10)

,date,store,item,sales,Date,year,month,day,dayofweek,weekofyear,quarter,is_weekend,Lag_1
0,2013-01-01,1,1,13,2013-01-01,2013,1,1,1,1,1,0,NaN
1,2013-01-02,1,1,11,2013-01-02,2013,1,2,2,1,1,0,13.0
2,2013-01-03,1,1,14,2013-01-03,2013,1,3,3,1,1,0,11.0
3,2013-01-04,1,1,13,2013-01-04,2013,1,4,4,1,1,0,14.0
4,2013-01-05,1,1,10,2013-01-05,2013,1,5,5,1,1,1,13.0
5,2013-01-06,1,1,12,2013-01-06,2013,1,6,6,1,1,1,10.0
6,2013-01-07,1,1,10,2013-01-07,2013,1,7,0,2,1,0,12.0
7,2013-01-08,1,1,9,2013-01-08,2013,1,8,1,2,1,0,10.0
8,2013-01-09,1,1,12,2013-01-09,2013,1,9,2,2,1,0,9.0
9,2013-01-10,1,1,9,2013-01-10,2013,1,10,3,2,1,0,12.0

In [40]:
df['Lag_3'] = df['sales'].shift(3)
df.head(10)

,date,store,item,sales,Date,year,month,day,dayofweek,weekofyear,quarter,is_weekend,Lag_1,Lag_3
0,2013-01-01,1,1,13,2013-01-01,2013,1,1,1,1,1,0,NaN,NaN
1,2013-01-02,1,1,11,2013-01-02,2013,1,2,2,1,1,0,13.0,NaN
2,2013-01-03,1,1,14,2013-01-03,2013,1,3,3,1,1,0,11.0,NaN
3,2013-01-04,1,1,13,2013-01-04,2013,1,4,4,1,1,0,14.0,13.0
4,2013-01-05,1,1,10,2013-01-05,2013,1,5,5,1,1,1,13.0,11.0
5,2013-01-06,1,1,12,2013-01-06,2013,1,6,6,1,1,1,10.0,14.0
6,2013-01-07,1,1,10,2013-01-07,2013,1,7,0,2,1,0,12.0,13.0
7,2013-01-08,1,1,9,2013-01-08,2013,1,8,1,2,1,0,10.0,10.0
8,2013-01-09,1,1,12,2013-01-09,2013,1,9,2,2,1,0,9.0,12.0
9,2013-01-10,1,1,9,2013-01-10,2013,1,10,3,2,1,0,12.0,10.0

In [41]:
df['Lag_7'] = df['sales'].shift(7)
df.head(10)

,date,store,item,sales,Date,year,month,day,dayofweek,weekofyear,quarter,is_weekend,Lag_1,Lag_3,Lag_7
0,2013-01-01,1,1,13,2013-01-01,2013,1,1,1,1,1,0,NaN,NaN,NaN
1,2013-01-02,1,1,11,2013-01-02,2013,1,2,2,1,1,0,13.0,NaN,NaN
2,2013-01-03,1,1,14,2013-01-03,2013,1,3,3,1,1,0,11.0,NaN,NaN
3,2013-01-04,1,1,13,2013-01-04,2013,1,4,4,1,1,0,14.0,13.0,NaN
4,2013-01-05,1,1,10,2013-01-05,2013,1,5,5,1,1,1,13.0,11.0,NaN
5,2013-01-06,1,1,12,2013-01-06,2013,1,6,6,1,1,1,10.0,14.0,NaN
6,2013-01-07,1,1,10,2013-01-07,2013,1,7,0,2,1,0,12.0,13.0,NaN
7,2013-01-08,1,1,9,2013-01-08,2013,1,8,1,2,1,0,10.0,10.0,13.0
8,2013-01-09,1,1,12,2013-01-09,2013,1,9,2,2,1,0,9.0,12.0,11.0
9,2013-01-10,1,1,9,2013-01-10,2013,1,10,3,2,1,0,12.0,10.0,14.0

In [42]:
df['sales'].shift(1).rolling(3).mean()

0               NaN
1               NaN
2               NaN
3         12.666667
4         12.666667
            ...
912995    56.000000
912996    51.666667
912997    54.333333
912998    65.333333
912999    65.000000
Name: sales, Length: 913000, dtype: float64

In [ ]:
df['diff1'] = df['sales'].diff(1)
df

,date,store,item,sales,Date,year,month,day,dayofweek,weekofyear,quarter,is_weekend,Lag_1,Lag_3,Lag_7,diff1
0,2013-01-01,1,1,13,2013-01-01,2013,1,1,1,1,1,0,NaN,NaN,NaN,NaN
1,2013-01-02,1,1,11,2013-01-02,2013,1,2,2,1,1,0,13.0,NaN,NaN,-2.0
2,2013-01-03,1,1,14,2013-01-03,2013,1,3,3,1,1,0,11.0,NaN,NaN,3.0
3,2013-01-04,1,1,13,2013-01-04,2013,1,4,4,1,1,0,14.0,13.0,NaN,-1.0
4,2013-01-05,1,1,10,2013-01-05,2013,1,5,5,1,1,1,13.0,11.0,NaN,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912995,2017-12-27,10,50,63,2017-12-27,2017,12,27,2,52,4,0,41.0,76.0,51.0,22.0
912996,2017-12-28,10,50,59,2017-12-28,2017,12,28,3,52,4,0,63.0,51.0,63.0,-4.0
912997,2017-12-29,10,50,74,2017-12-29,2017,12,29,4,52,4,0,59.0,41.0,75.0,15.0
912998,2017-12-30,10,50,62,2017-12-30,2017,12,30,5,52,4,1,74.0,63.0,70.0,-12.0
912999,2017-12-31,10,50,82,2017-12-31,2017,12,31,6,52,4,1,62.0,59.0,76.0,20.0

In [50]:
df['percentage_change'] = df['sales'].pct_change() * 100
df.head(10)

,date,store,item,sales,Date,year,month,day,dayofweek,weekofyear,quarter,is_weekend,Lag_1,Lag_3,Lag_7,diff1,ptc_change,percentage_change
0,2013-01-01,1,1,13,2013-01-01,2013,1,1,1,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-01-02,1,1,11,2013-01-02,2013,1,2,2,1,1,0,13.0,NaN,NaN,-2.0,-15.384615,-15.384615
2,2013-01-03,1,1,14,2013-01-03,2013,1,3,3,1,1,0,11.0,NaN,NaN,3.0,27.272727,27.272727
3,2013-01-04,1,1,13,2013-01-04,2013,1,4,4,1,1,0,14.0,13.0,NaN,-1.0,-7.142857,-7.142857
4,2013-01-05,1,1,10,2013-01-05,2013,1,5,5,1,1,1,13.0,11.0,NaN,-3.0,-23.076923,-23.076923
5,2013-01-06,1,1,12,2013-01-06,2013,1,6,6,1,1,1,10.0,14.0,NaN,2.0,20.000000,20.000000
6,2013-01-07,1,1,10,2013-01-07,2013,1,7,0,2,1,0,12.0,13.0,NaN,-2.0,-16.666667,-16.666667
7,2013-01-08,1,1,9,2013-01-08,2013,1,8,1,2,1,0,10.0,10.0,13.0,-1.0,-10.000000,-10.000000
8,2013-01-09,1,1,12,2013-01-09,2013,1,9,2,2,1,0,9.0,12.0,11.0,3.0,33.333333,33.333333
9,2013-01-10,1,1,9,2013-01-10,2013,1,10,3,2,1,0,12.0,10.0,14.0,-3.0,-25.000000,-25.000000